language: java
sudo: true
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - cobertura

script: "mvn clean compile cobertura:instrument test && cobertura-merge */target/cobertura/*.ser && cobertura-report --destination target/cobertura --format xml"

after_success:
  - bash <(curl -s https://codecov.io/bash)
